#!/bin/bash

FOLDER='execution'
if [[ "$#" > "1" ]]; then
  FOLDER=$2
fi

DELAY=80
if [[ "$#" > "2" ]]; then
  DELAY=$3
fi

SLEEP=`expr match "$1" '.*[0-9]*_delay_'`
if [[ $SLEEP > 0 ]]; then
  f=$1
  END=`expr index "$f" m`
  SLEEP=${f:$SLEEP:$END - 2 - $SLEEP}
  sleep $SLEEP
elif [[ -f "$1" ]]; then
  cat $1 | xmacroplay -d $DELAY :0 > /dev/null
elif [[ -f "./$FOLDER/$1" ]]; then
  cat ./$FOLDER/$1 | xmacroplay -d $DELAY :0 > /dev/null
else
  cat ./$FOLDER/$1.mac | xmacroplay -d $DELAY :0 > /dev/null
fi
