#!/bin/bash

TIMES=1
if [[ "$#" > "0" ]]; then
  TIMES=$1
fi

for f in before/*.mac; do
  if [[ $f != 'before/*.mac' ]]; then
    ./play $f
  fi;
done

COUNT=0
while [[ "$COUNT" < "$TIMES" ]]; do
  for f in execution/*.mac; do
    if [[ $f != 'execution/*.mac' ]]; then
      ./play $f
    fi;
  done
  (( COUNT++ ))
done

for f in after/*.mac; do
  if [[ $f != 'after/*.mac' ]]; then
    ./play $f
  fi;
done
