#!/bin/bash

TIMES=1
if [[ "$#" > "0" ]]; then
  TIMES=$1
fi

for f in before/*; do
  ./play $f
done

COUNT=0
while [[ "$COUNT" < "$TIMES" ]]; do
  for f in execution/*; do
    ./play $f
  done
  (( COUNT++ ))
done

for f in after/*; do
  ./play $f
done
