#!/bin/bash

call_play() {
  dir=$1
  for f in $dir; do
    if [[ `expr index $f '*'` == 0 ]]; then
      if [[ $DEBUG == TRUE ]]; then
        echo -n "Next to run: "
        echo -n $f
        echo -n " (press Enter to continue)"
        read
      fi
      ./play -d $DELAY $f
    fi;
  done
}

PROG_NAME=$(basename $0)
DEBUG=false
TIMES=1
DELAY=100

while getopts r:d:g OPTION
do
  case ${OPTION} in
      d) DELAY=${OPTARG};;
      g) DEBUG=TRUE;;
      r) TIMES=${OPTARG};;
    \?) echo "Usage: ${PROG_NAME} [-r TIMES_TO_REPEAT] [-d XMACRO_DELAY] [-g]"
         exit 2;;
  esac
done

call_play before/*.mac

COUNT=0
while [[ "$COUNT" < "$TIMES" ]]; do
  call_play 'execution/*.mac'
  (( COUNT++ ))
done

call_play after/*.mac
